version: '2'
services:
  web:
    container_name: web
    image: nginx
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx-proxy/.
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
    links:
     - web 

